// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  stat: string;
  stat__name: string;
  stat__round: string;
}
export const cssExports: CssExports;
export default cssExports;
