// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  loader: string;
  loader__animation: string;
  loader__container: string;
  loader__image: string;
  swing: string;
}
export const cssExports: CssExports;
export default cssExports;
