// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  button_danger: string;
  button_default: string;
  button_small: string;
  button_success: string;
}
export const cssExports: CssExports;
export default cssExports;
