// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  menu__item: string;
  menu__link: string;
  menu__link_state_active: string;
  menu__list: string;
}
export const cssExports: CssExports;
export default cssExports;
