// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pokemonModal: string;
  pokemonModal__container: string;
  pokemonModal__content: string;
  pokemonModal__gallery: string;
  pokemonModal__image: string;
  pokemonModal__item: string;
  pokemonModal__slogan: string;
  pokemonModal__types: string;
}
export const cssExports: CssExports;
export default cssExports;
