// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pokemonsColors_error: string;
  pokemonsColors_info: string;
  pokemonsColors_rose: string;
  pokemonsColors_success: string;
  pokemonsColors_warning: string;
}
export const cssExports: CssExports;
export default cssExports;
