// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pokemons: string;
  pokemons__container: string;
  pokemons__filter: string;
  pokemons__search: string;
  pokemons__slogan: string;
}
export const cssExports: CssExports;
export default cssExports;
