// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  home: string;
  home__container: string;
  home__content: string;
  home__description: string;
  home__image: string;
  home__information: string;
  home__slogan: string;
  home__wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
