// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  heading: string;
  heading__1: string;
  heading__2: string;
  heading__3: string;
  heading__4: string;
  heading__5: string;
  heading__6: string;
}
export const cssExports: CssExports;
export default cssExports;
