// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  progress: string;
  progress__bar: string;
  progress__line: string;
  progress__line_warning: string;
}
export const cssExports: CssExports;
export default cssExports;
