// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pagination: string;
  pagination__button: string;
  pagination__button_next: string;
  pagination__button_prev: string;
  pagination__item: string;
  pagination__list: string;
}
export const cssExports: CssExports;
export default cssExports;
