// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  abilities: string;
  abilities__header: string;
  abilities__item: string;
  abilities__list: string;
}
export const cssExports: CssExports;
export default cssExports;
