// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  characteristics: string;
  characteristics__item: string;
  characteristics__slogan: string;
  characteristics__value: string;
}
export const cssExports: CssExports;
export default cssExports;
