// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  footer: string;
  footer__container: string;
  footer__copyright: string;
  footer__description: string;
}
export const cssExports: CssExports;
export default cssExports;
