// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  card__gallery: string;
  card__gallery_view_error: string;
  card__gallery_view_info: string;
  card__gallery_view_rose: string;
  card__gallery_view_success: string;
  card__gallery_view_warning: string;
  card__image: string;
  card__info: string;
  card__slogan: string;
  card__stats: string;
}
export const cssExports: CssExports;
export default cssExports;
