// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pokemonBackground: string;
  pokemonBackground_error: string;
  pokemonBackground_info: string;
  pokemonBackground_rose: string;
  pokemonBackground_success: string;
  pokemonBackground_warning: string;
}
export const cssExports: CssExports;
export default cssExports;
