// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  notFound: string;
  notFound__button: string;
  notFound__container: string;
  notFound__contrast: string;
  notFound__description: string;
  notFound__gallery: string;
  notFound__image: string;
  notFound__parallax: string;
  notFound__slogan: string;
}
export const cssExports: CssExports;
export default cssExports;
